### ISSUE TITLE
DATE() doesn't work properly

### ISSUE THREAD

**Issue by sanchopanca** [spitbol/x64#1]
It seems like DATE() function doesn't work as expected.
Let's assume I have following code:

```
    OUTPUT = DATE()
END
```

The result of execution of this program is always the same:

```
$ spitbol date.spt
01/01/70 04:00:00
$ date
Fri Oct 16 10:33:27 AST 2015
```

I'm using Linux Mint 17.2 x64

```
$ uname -a
Linux sanchopanca-N551JM 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

P. S. I'm using prebuilt binary `sbl_unix`

**Comment by daveshields** [comment]
Thanks for the note.

RIght you are. I plan to fix it shortly.

thanks,
dave

**Comment by daveshields** [comment]
I have just updated osint/sysdt.c to fix this. This has been tested on Linux, but not yet on OSX.

There was also problem with TIME(), which was always returning the same value. This has been fixed in osint/systm.c
