### ISSUE TITLE
Ubuntu 18.04  problem with running float.sbl causing overflow or underflow

### ISSUE THREAD

**Issue by osmanfb** [spitbol/x64#14]
I built the x64 spitbol on my ubuntu 18.04 laptop. Building and running sanitychecjk  went ok and I installed it. But trying it on the files in the test subdirectory, I am having a problem with float.sbl file. 
../sbl float.sbl
5.              expect 5.0

test/float_orig.sbl(9) : error 264 -- subtraction caused real overflow

in file              test/float_orig.sbl
in line              9
in statement         9
stmts executed       9
execution time msec  0
in line              0
memory used (bytes)  12792
memory left (bytes)  249344
------------------------------------------------------------
same thing happens with the spitbol executable from the bin subdir.. But if build the 32 bit version from github/x32  then that spitbol runs the float.sbl without any problems. Also if switch floats to integers, it also works.
What could be the problem/where to look ???
TIA

**Comment by CheyenneWills** [comment]
I'm also running into a similar problem, but am getting a segfault around label gts26 with just a simple:

   x = 2.0 'a'
end

**Comment by CheyenneWills** [comment]
I think I might know what is going on and I'm investigating a solution (possible misplacement of a read-write area into a read only segment)

**Comment by CheyenneWills** [comment]
Found the problem and have a fix.  It wasn't what I had thought above.

Some of the internal calls to C functions from the assembly code need to preserve some registers that get clobbered (I believe that this might be a Linux vs Windows difference).  

Adding a couple of pushes prior to the calls and pops afterwards appears to fix the problem.

**Comment by CheyenneWills** [comment]
Pull Request #15 I believe fixes the problem.  The branch contains some of the other patches that I've worked on and includes some general (and minor) build cleanup.

**Comment by osmanfb** [comment]
Thanks for looking into and fixing but how long does it take github to update the master branch? I just cloned the master into a new folder and  float.sbl still causing the underflow.

**Comment by CheyenneWills** [comment]
> Thanks for looking into and fixing but how long does it take github to update the master branch? I just cloned the master into a new folder and float.sbl still causing the underflow.

I'm waiting to hear back from Dave Shields who has commit authority.  In the meantime you can use what's in the above pull request.

**Comment by osmanfb** [comment]
I did. I changed sbl.asm, int.asm, int.dcl as the diffs showed. same problem. looks like clobbering happens on the  output =   statements,  Variable calculations of any complexity that I tried worked ok as long as the output statement did not contain any float ops. I also cloned bootstrap and it did not work either. Looks like the above asm and dcl files are created each time make is executed. So the changes are overwritten.

**Comment by daveshields** [comment]
Cheyenne,

Thanks for all your work. I reviewed your prior emails and noted that I
invited to to become a committer on November 4, so please feel free to pull
your patches into the master.

thanks,
dave

**Comment by CheyenneWills** [comment]
> Cheyenne, Thanks for all your work. I reviewed your prior emails and noted that I invited to to become a committer on November 4, so please feel free to pull your patches into the master. thanks, dave

Thanks Dave.  It appears that I don't have write access to the spitbol/x64 repository, just read access so I can't complete the pull request.

**Comment by daveshields** [comment]
Cheyenne,

Right you are. Sorry about that.

I just changed your role to Owner. I think that should do it.

dave

**Comment by CheyenneWills** [comment]
The fix is now in master.

**Comment by CheyenneWills** [comment]
::sigh:: still a minor problem (probably a missed call).

**Comment by daveshields** [comment]
FYI,

sanity-check doesn't test or require any floating point arithmetic,
since SPITBOL can be configured to not support floating point arithmetic.
It just checks that the system is capable of rebuilding itself, and that
the rebuilt system can also rebuild itself. All this is to make sure some
nasty bug doesn't creep in only to show up later.

thanks,
dave

**Comment by CheyenneWills** [comment]
I found the problem with the floating point.  There needed to be some checks for floating point "problems" with some of the operations (+-/*).  I have a "fix" for that as well..

New PR coming in for that..

**Comment by CheyenneWills** [comment]
PR #16 should better handle the problem with some floating point operations.

I was getting the error:  "test/float.sbl(9) : error 264 -- subtraction caused real overflow".  The above PR should fix that.

**Comment by osmanfb** [comment]
as of Jan 04, 2 pm the master branch still causing the floating point exception. I checked that having bunch of lines of float operations does not cause the exception. But multiple "output = " with floats does.    x = 2.0
   y = 5.0
   z = x + y * ( y - 1.0)
   w = x * y * z
   output = w
   output = x
   output = x + y
end
the last output cause an exception. If taken out runs ok.

**Comment by CheyenneWills** [comment]
> as of Jan 04, 2 pm the master branch still causing the floating point exception. I checked that having bunch of lines of float operations does not cause the exception. But multiple "output = " with floats does. x = 2.0 y = 5.0 z = x + y * ( y - 1.0) w = x * y * z output = w output = x output = x + y end the last output cause an exception. If taken out runs ok.

I've merged the latest changes (PR #16) into master.

**Comment by osmanfb** [comment]
thanks Cheyenne. master is working ok now (Jan 6, 00:28). The only thing is the pre-built bin/sbl is causing "illegal instruction" and maybe should not be included. Also a few lines could be added to the README  to do a make bootsbl  first and then follow with make BASEBOL=./bootsbl  and finally  make bininst  to copy the sbl to the bin directory.
