### ISSUE TITLE
Running any .spl file always results in segfault

### ISSUE THREAD

**Issue by EvanSandersd** [spitbol/x64#18]
Downloaded the 64x version of SPITBOL using Debian 11 Linux, arm64.

Instructions included in the README also does not seem to align with the instructions on the GITHUB. Regardless, after following the README, it still produces unexpected results.

The file location is "usr/local/bin/spitbol". Inputting the command "$spitbol [file name]" in the native terminal does not produce expected results under any circumstances. It will always produce a segfault, even after chmod +755 following a successful build (as defined in the instructions in the README included). 

Attempts at opening any .spl, .sno, or .spx file results in segfault. 

Typing in the command "$spitbol" produces expected results as defined in the README, displaying the version number (v4.0) along with the various built-in shortcut commands.

Attempts at running the "sanity-check" included in the SPITBOL file always results in segfault.

Debian 11 is capable of running .sno files when using SNOBOL5.

**Comment by CheyenneWills** [comment]
Am I correct in assuming that you downloaded the tar.gz or .zip file from the Releases link and did not download/build from source?

**Comment by EvanSandersd** [comment]
Yes, you are correct.

**Comment by CheyenneWills** [comment]
I have updated the tar.,gz / zip files to release V4.0a which should contain the fix for this problem.

**Comment by CheyenneWills** [comment]
I've pushed a new development branch that has some improvements.

Once it has been tested, I will be promoting that branch to the main branch.

**Comment by CheyenneWills** [comment]
This issue is a dup of #11
