### ISSUE TITLE
Is development of spitbol completely halted?

### ISSUE THREAD

**Issue by aksr** [spitbol/x64#19]
Seeing there is no commits after 2020 in any of the repositories from Dave Shields, I was wondering what is happening.

Does anyone knows what happened?

**Comment by CheyenneWills** [comment]
I have been trying to get in touch with Dave Shields so see how he wants to address some items.  If there is something urgent, I do have commit authority

**Comment by aksr** [comment]
Is everything OK, do you know?

Nothing is urgent, I just recently discovered ``SNOBOL4``, and I'm very impressed with it.
I'm just disappointed the *allegedly*-best implementation isn't complete.

Anyway, if you want to test something, I'm here.

**Comment by daveshields** [comment]
I no longer work on SPITBOL

Dave

**Comment by aksr** [comment]
If it's not a problem, could You tell us why?

**Comment by CheyenneWills** [comment]
> I no longer work on SPITBOL Dave

Dave, I sent you a private email.

Cheyenne

**Comment by CheyenneWills** [comment]
To answer the question.. development will continue for Spitbol.

**Comment by aksr** [comment]
@CheyenneWills: Thank you. If it's not a problem, could you be more specific? What's next to be worked on?
Maybe loading of modules or external functions?

**Comment by CheyenneWills** [comment]
> @CheyenneWills: Thank you. If it's not a problem, could you be more specific? What's next to be worked on? Maybe loading of modules or external functions?

At the moment it will probably be just some needed housekeeping and minor cleanup

**Comment by CheyenneWills** [comment]
As per a conversation with David Shields, I'm taking over the maintenance of the SPITBOL project. I have been in contact with both Mark Emmer and Robert Goldberg.

I've just:
- Rename the master branch to main
- Created a branch "dshields" and tagged it to "maintainer-turnover" to preserve the last point of David's stewardship.
- Pushed a couple of minor fixes and created the 4.0a tag and release

Going forward, there are some immediate housekeeping items I would like to do.  Some of which will be consolidating or renaming some of the repositories.

Longer term the one item I would like to research is to see if LLVM could be used as the target for the minimal translation.  This might open up the ability to easily implement unicode and target more architectures.

**Comment by CheyenneWills** [comment]
Just a note that I am actively (though slowly) working through some implementation problems and will be pushing updates.

So to answer this particular ticket, yes there still is ongoing development for spitbol.
