### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by VulcanTourist** [spitbol/x64#23]
Thank you for helping preserve and keep this language alive.  My personal experience with it was brief but formative, and it would be a shame for it never to be formative for anyone else.

I took a summer job - my first "career" job - as a programmer working at a banknote printing company.  They used PDP 11/70 systems running a custom BOSS operating system, and SPITBOL as the language to direct and control the operation of the phototypesetting machines.  It was all entirely new to me, including SPITBOL.  I found it to be an odd language with a strange syntax which was nevertheless adept at the one job it did best: pattern matching.

Thank you for preserving this curious language.

**Comment by CheyenneWills** [comment]
Thank you.

There will be some updates coming soon, more fixes for floating point, and a bit longer term some new (old) features enabled.
