### ISSUE TITLE
Provided 4.0c binary crashes on some systems, but works when rebuilt on that system

### ISSUE THREAD

**Issue by CheyenneWills** [spitbol/x64#25]
Need more information

**Comment by CheyenneWills** [comment]
In issue #21, it was reported that 4.0c crashed with the provided binary, but works when rebuilt.

I need additional information.

- Any messages provided during the crash
- the output of /proc/cpu
- glibc's level.
- And if possible the location of the crash.  This might be possible running gdb and capturing the information when the crash happens.
```
gdb {path to the provided spitbol binary}
    set args {your program}
    run
    info registers
    bt
```

**Comment by haijinSk** [comment]
In my case the precompiled, provided 4.0c binary works, so I can't help in a straightforward way... But for the record, my case: 

Ubuntu 22.04.3 LTS, Intel Core i5-6500 CPU @ 3.20GHz × 4.

And the example:

```
 x = 3
 y = ln(x)
 output = y "= ln(" x ")"
end
```
yields:

`1.09861228866811= ln(3)`

**Comment by CheyenneWills** [comment]
https://github.com/spitbol/x64/issues/21#issuecomment-1779747522

**Comment by CheyenneWills** [comment]
Looking at the information that was appended in #21 it appears the problem is with my build environment.  The build is a static build and statically includes the stdc library and the math library that was built on my system targeting my native CPU, which appears to include additional instructions than the CPU that is having problems.

I believe that rebuilding using non-static libraries should fix the problem.  There has been an issue with spitbol as non-static, but I believe that I've now solved that problem.  I will need to do additional testing to verify that the fix I have will work.
