### ISSUE TITLE
Seg Fault in Linux x64 under Win 10

### ISSUE THREAD

**Issue by dmausner** [spitbol/x64#5]
Using new Ubuntu installed in Win 10 x64 with this signature:
dave@PC5W:~/work/rockwell$ uname -a
Linux PC5W 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

The README says that a static-linked x64 executable is in GIT ./bin, so I downloaded "sbl".

Renamed "sbl" to "spitbol", installed in /usr/local/bin.  Running "spitbol" (no args) produces usage message, as expected.  But when testing it using standard input (I would have entered just "end"):

dave@PC5W:~/work/rockwell$ spitbol -
Segmentation fault (core dumped)

**Comment by CheyenneWills** [comment]
At the moment, I'm not sure what the status of trying to build for WIndows is.

**Comment by dmausner** [comment]
Five and half years later, a reminder !  Thank you.  I re-downloaded the 
Feb 2023 edition from GIT, did the <makefile install>, and it works 
properly in Windows 10 Ubuntu.  Whatever !

--
Dave Mausner.  +1-312-925-3694.
Rem tene; verba sequentur -- Cato.
Just show me the code -- Dave.


------ Original Message ------
From "Cheyenne Wills" ***@***.***>
To "spitbol/x64" ***@***.***>
Cc "Dave Mausner" ***@***.***>; "Author" 
***@***.***>
Date 2023-06-14 9:11:38 PM
Subject Re: [spitbol/x64] Seg Fault in Linux x64 under Win 10 (#5)

**Comment by CheyenneWills** [comment]
So, were you able to do a successful build for Windows?

You might also want to grab the development branch as it has several important fixes (mainly floating point)
