### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by octonion** [spitbol/x64#8]
It looks like the demos won't run unless "END" is replaced with "end". Is this a bug or a feature?

**Comment by arblake** [comment]
I am doing some searching but cannot find where in sources 'end' is detected.

**Comment by daveshields** [comment]
Adrian,

In SBL.MIN, look for string 'v_end'. That is label of block for end
statement. Look for references to it in scan/compile part and
see how it is handled there.

thanks,
dave

**Comment by CheyenneWills** [comment]
Old issue.

The root problem is how case folding is handled.

There is probably room for some improvement in this area and I will be investigating some ways to improve this (or at least get a better handle on some of the implementation and get better documentation on the behavior).
